# Generated by Django 6.0 on 2026-01-08 22:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categoria', models.CharField(choices=[('moto_taxi', 'Moto Táxi'), ('moto_entrega', 'Moto Entrega')], max_length=50)),
                ('icone', models.CharField(default='fa-motorcycle', max_length=50)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('imagem_secundaria', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('descricao_curta', models.TextField()),
                ('descricao_longa', ckeditor.fields.RichTextField()),
                ('caracteristicas', models.TextField(help_text='Separe cada característica com vírgula')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('meta_titulo', models.CharField(blank=True, max_length=200)),
                ('meta_descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='website.servico')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
