# Generated by Django 6.0 on 2026-01-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_servico_beneficioservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficioservico',
            name='icone',
            field=models.CharField(default='fa-check', max_length=50),
        ),
        migrations.AlterField(
            model_name='servico',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Separe cada característica com vírgula'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao_longa',
            field=models.TextField(),
        ),
    ]
