# Generated by Django 6.0 on 2026-01-02 15:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('MOTOTAXISTA', 'Mototaxista')], max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('EM_CURSO', 'Em Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='usuarios.cliente')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas', to='usuarios.moto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nota', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('corrida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='usuarios.corrida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mototaxista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('telefone', models.CharField(max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mototaxista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='moto',
            name='mototaxista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='usuarios.mototaxista'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='mototaxista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas', to='usuarios.mototaxista'),
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('idioma_preferido', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('fr', 'Francês')], default='pt', max_length=10)),
                ('metodo_pagamento_preferido', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('MBWAY', 'MBWay'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência')], default='DINHEIRO', max_length=20)),
                ('total_corridas', models.PositiveIntegerField(default=0)),
                ('total_gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('membro_desde', models.DateTimeField(auto_now_add=True)),
                ('casa_endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('trabalho_endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('receber_notificacoes_push', models.BooleanField(default=True)),
                ('receber_promocoes_email', models.BooleanField(default=False)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='usuarios.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilMototaxista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bi_numero', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do BI')),
                ('bi_frente', models.ImageField(blank=True, null=True, upload_to='documentos/bi/frente/')),
                ('bi_verso', models.ImageField(blank=True, null=True, upload_to='documentos/bi/verso/')),
                ('carta_conducao_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('carta_conducao_validade', models.DateField(blank=True, null=True)),
                ('carta_conducao_foto', models.ImageField(blank=True, null=True, upload_to='documentos/carta_conducao/')),
                ('classificacao_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_corridas', models.PositiveIntegerField(default=0)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('banco_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('conta_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_atualizacao_localizacao', models.DateTimeField(blank=True, null=True)),
                ('aceita_corridas_longas', models.BooleanField(default=True)),
                ('raio_atendimento_km', models.PositiveIntegerField(default=10, help_text='Raio máximo em km para aceitar corridas')),
                ('mototaxista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='usuarios.mototaxista')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
